"""empty message

Revision ID: 17c36d0e1a19
Revises: 98eed65a1d07
Create Date: 2021-07-09 15:36:26.607914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c36d0e1a19'
down_revision = '98eed65a1d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locator', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('user_locator', sa.Column('cpf_hash', sa.String(), nullable=False))
    op.add_column('user_locator', sa.Column('address', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user_locator', ['cpf_hash'])
    op.drop_column('user_locator', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locator', sa.Column('adress', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_locator', type_='unique')
    op.drop_column('user_locator', 'address')
    op.drop_column('user_locator', 'cpf_hash')
    op.drop_column('user_locator', 'password_hash')
    # ### end Alembic commands ###
