"""empty message

Revision ID: 4b9ce70f60d1
Revises: 10b8d566edb9
Create Date: 2021-07-14 22:05:15.547819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9ce70f60d1'
down_revision = '10b8d566edb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'unavaliable_date', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unavaliable_date', type_='unique')
    # ### end Alembic commands ###
