"""empty message

Revision ID: 5e0a2c22d6d3
Revises: c039429a9027
Create Date: 2021-07-09 15:47:26.620812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0a2c22d6d3'
down_revision = 'c039429a9027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_locator', 'name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    op.alter_column('user_locator', 'last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    op.alter_column('user_locator', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_locator', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_locator', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_locator', 'cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_locator', 'cep',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user_locator', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_locator', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_locator', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_locator', 'last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    op.alter_column('user_locator', 'name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    # ### end Alembic commands ###
