"""empty message

Revision ID: 80eb5aeeccda
Revises: 4b9ce70f60d1
Create Date: 2021-07-15 18:51:34.751575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80eb5aeeccda'
down_revision = '4b9ce70f60d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_locator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=150), nullable=False),
    sa.Column('avaliation', sa.Integer(), nullable=True),
    sa.Column('user_locator_id', sa.Integer(), nullable=False),
    sa.Column('user_lessee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_lessee_id'], ['user_lessee.id'], ),
    sa.ForeignKeyConstraint(['user_locator_id'], ['user_locator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_locator')
    # ### end Alembic commands ###
