"""empty message

Revision ID: 884441ec81e9
Revises: d53760a4cf21
Create Date: 2021-07-20 20:29:50.845385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884441ec81e9'
down_revision = 'd53760a4cf21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lessee', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('user_locator', sa.Column('phone_number', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_locator', 'phone_number')
    op.drop_column('user_lessee', 'phone_number')
    # ### end Alembic commands ###
