"""empty message

Revision ID: 98eed65a1d07
Revises: d47e62b4ad71
Create Date: 2021-07-09 15:31:06.990097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98eed65a1d07'
down_revision = 'd47e62b4ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locator', sa.Column('last_name', sa.String(length=55), nullable=True))
    op.drop_column('user_locator', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locator', sa.Column('password', sa.VARCHAR(length=55), autoincrement=False, nullable=True))
    op.drop_column('user_locator', 'last_name')
    # ### end Alembic commands ###
