"""empty message

Revision ID: b33696480e1a
Revises: 423e153fff69
Create Date: 2021-07-21 22:53:46.118837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33696480e1a'
down_revision = '423e153fff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unavaliable_date_date_key', 'unavaliable_date', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unavaliable_date_date_key', 'unavaliable_date', ['date'])
    # ### end Alembic commands ###
