"""empty message

Revision ID: c039429a9027
Revises: 17c36d0e1a19
Create Date: 2021-07-09 15:41:17.014212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c039429a9027'
down_revision = '17c36d0e1a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('insurer_number', sa.String(length=20), nullable=False))
    op.add_column('car', sa.Column('review_date', sa.Date(), nullable=False))
    op.add_column('car', sa.Column('withdrawal_place', sa.String(length=255), nullable=False))
    op.add_column('car', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('car', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('car', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'car', 'user_locator', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'user_id')
    op.drop_column('car', 'state')
    op.drop_column('car', 'city')
    op.drop_column('car', 'withdrawal_place')
    op.drop_column('car', 'review_date')
    op.drop_column('car', 'insurer_number')
    # ### end Alembic commands ###
