"""empty message

Revision ID: c7880aab5f41
Revises: f1d929d13645
Create Date: 2021-07-14 21:24:07.850365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7880aab5f41'
down_revision = 'f1d929d13645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavaliable_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unavaliable_date')
    # ### end Alembic commands ###
