"""empty message

Revision ID: d47e62b4ad71
Revises: 
Create Date: 2021-07-09 11:37:02.928696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47e62b4ad71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('car_plate', sa.String(length=11), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('insurer', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_locator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=55), nullable=True),
    sa.Column('adress', sa.Text(), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_locator')
    op.drop_table('car')
    # ### end Alembic commands ###
