"""empty message

Revision ID: d53760a4cf21
Revises: e3c6efeaa592
Create Date: 2021-07-20 20:00:55.124158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53760a4cf21'
down_revision = 'e3c6efeaa592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('license_plate', sa.String(length=7), nullable=False))
    op.add_column('car', sa.Column('trunk_volume', sa.Integer(), nullable=True))
    op.drop_constraint('car_car_plate_key', 'car', type_='unique')
    op.create_unique_constraint(None, 'car', ['license_plate'])
    op.drop_column('car', 'car_plate')
    op.drop_column('car', 'thunk_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('thunk_volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('car_plate', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'car', type_='unique')
    op.create_unique_constraint('car_car_plate_key', 'car', ['car_plate'])
    op.drop_column('car', 'trunk_volume')
    op.drop_column('car', 'license_plate')
    # ### end Alembic commands ###
