"""fix: CarModel - car_plate and trunk_volume

Revision ID: e2174250b5d9
Revises: 
Create Date: 2021-07-11 22:54:06.323327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2174250b5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lessee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=55), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('cnh', sa.Text(), nullable=False),
    sa.Column('cpf_encrypt', sa.String(length=14), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_encrypt'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_locator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('cpf_encrypt', sa.Unicode(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_encrypt'),
    sa.UniqueConstraint('email')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('car_plate', sa.String(length=7), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('trunk_volume', sa.Integer(), nullable=True),
    sa.Column('insurer', sa.String(length=55), nullable=False),
    sa.Column('insurer_number', sa.String(length=20), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('withdrawal_place', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_locator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_lessee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('avaliation', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('lesse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['lesse_id'], ['user_lessee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_lessee')
    op.drop_table('car')
    op.drop_table('user_locator')
    op.drop_table('user_lessee')
    # ### end Alembic commands ###
