"""empty message

Revision ID: e3c6efeaa592
Revises: 163ad6bd412b
Create Date: 2021-07-15 22:21:07.647235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c6efeaa592'
down_revision = '163ad6bd412b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.create_unique_constraint(None, 'car', ['car_plate'])
    op.add_column('record_lessee', sa.Column('lessee_id', sa.Integer(), nullable=False))
    op.alter_column('record_lessee', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('record_lessee', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('record_lessee_lesse_id_fkey', 'record_lessee', type_='foreignkey')
    op.create_foreign_key(None, 'record_lessee', 'user_lessee', ['lessee_id'], ['id'])
    op.drop_column('record_lessee', 'lesse_id')
    op.alter_column('record_locator', 'comment',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_unique_constraint(None, 'user_lessee', ['cnh'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_lessee', type_='unique')
    op.alter_column('record_locator', 'comment',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.add_column('record_lessee', sa.Column('lesse_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'record_lessee', type_='foreignkey')
    op.create_foreign_key('record_lessee_lesse_id_fkey', 'record_lessee', 'user_lessee', ['lesse_id'], ['id'])
    op.alter_column('record_lessee', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('record_lessee', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('record_lessee', 'lessee_id')
    op.drop_constraint(None, 'car', type_='unique')
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avaliation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lessee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name='record_car_id_fkey'),
    sa.ForeignKeyConstraint(['lessee_id'], ['user_lessee.id'], name='record_lessee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='record_pkey')
    )
    # ### end Alembic commands ###
